// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF5qxO93rkHu3pyxo5aBVOANqJLaGyrfE',
    appId: '1:688587508865:web:f026835135269f05075180',
    messagingSenderId: '688587508865',
    projectId: 'petal-count-dev',
    authDomain: 'petal-count-dev.firebaseapp.com',
    storageBucket: 'petal-count-dev.firebasestorage.app',
    measurementId: 'G-XS3JL7RHGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQ-y1tL56alZBA_eWQ7hqimX7U2vbrfw',
    appId: '1:688587508865:android:be2855c3ed2b4cac075180',
    messagingSenderId: '688587508865',
    projectId: 'petal-count-dev',
    storageBucket: 'petal-count-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfeizWwhMjjz0d7RIXuPLDPssQmG4JHg',
    appId: '1:688587508865:ios:a04a0bd73e2b55ce075180',
    messagingSenderId: '688587508865',
    projectId: 'petal-count-dev',
    storageBucket: 'petal-count-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.petalCount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtfeizWwhMjjz0d7RIXuPLDPssQmG4JHg',
    appId: '1:688587508865:ios:a04a0bd73e2b55ce075180',
    messagingSenderId: '688587508865',
    projectId: 'petal-count-dev',
    storageBucket: 'petal-count-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.petalCount',
  );
}
