// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeULttE9FqiF6i43lrTHjSSGuwETEYXDo',
    appId: '1:847947122489:web:ba169e6701570bb2ef0ae8',
    messagingSenderId: '847947122489',
    projectId: 'petal-count-prod',
    authDomain: 'petal-count-prod.firebaseapp.com',
    storageBucket: 'petal-count-prod.firebasestorage.app',
    measurementId: 'G-5T72CGNFFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3zDw-4rWJcLrP-GrBosWpq8EZIyx0Wc',
    appId: '1:847947122489:android:144d8867e4c14281ef0ae8',
    messagingSenderId: '847947122489',
    projectId: 'petal-count-prod',
    storageBucket: 'petal-count-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfV7IBmsCNBL7RnW3Xy21tuCqP-mxVzw',
    appId: '1:847947122489:ios:daf6e9d38db8bacdef0ae8',
    messagingSenderId: '847947122489',
    projectId: 'petal-count-prod',
    storageBucket: 'petal-count-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.petalCount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfV7IBmsCNBL7RnW3Xy21tuCqP-mxVzw',
    appId: '1:847947122489:ios:daf6e9d38db8bacdef0ae8',
    messagingSenderId: '847947122489',
    projectId: 'petal-count-prod',
    storageBucket: 'petal-count-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.petalCount',
  );
}
